---
- name: Install and prepare Ansible
  hosts: all
  become: true
  tasks:

  - name: Update and upgrade
    ansible.builtin.apt:
      update_cache: true
      name:
        - git
        - sshpass
        - net-tools
        - joe
        - mc
      state: present

  - name: Install Ansible collections
    ansible.builtin.command:
      cmd: ansible-galaxy collection install community.zabbix community.grafana community.docker --force

  - name: Cloning Git repository
    ansible.builtin.git:
      repo: 'https://github.com/sposdknl/ansible02-grgalaxer.git'
      dest: /opt/repo

  - name: Bootstrap server configuration from repository
    ansible.builtin.command:
      cmd: ansible-playbook configure_servers.yml
      chdir: /opt/repo
    become: false
    register: configure_output

  - name: Print output from configure_servers playbook
    ansible.builtin.debug:
      var: configure_output.stdout_lines
